stage:
  global:
    # MIN_LOGGING_LEVEL: debug
    MIN_LOGGING_LEVEL: warning
  build:
    # https://experienceleague.adobe.com/docs/commerce-operations/tools/quality-patches-tool/release-notes.html
    QUALITY_PATCHES:
      - ACSD-46683
      - ACSD-47704
      - ACSD-47908
      - ACSD-48059
      - ACSD-48164
      - ACSD-48212
      - ACSD-48216
      - ACSD-48366
      - ACSD-48417
      - ACSD-48587
      - ACSD-48634
      - ACSD-48694
      - ACSD-48771
      - ACSD-48773
      - ACSD-48784
      - ACSD-48807
      - ACSD-48813
      - ACSD-48857
      - ACSD-48866
      - ACSD-49065
      - ACSD-49179
      - ACSD-49286
      - ACSD-49370
      - ACSD-49389
      - ACSD-49392
      - ACSD-49433
      - ACSD-49464
      - ACSD-49502
      - ACSD-49574
      - ACSD-49628
      - ACSD-49706
      - ACSD-49737
      - ACSD-49748
      - ACSD-49835
      - ACSD-49877
      - ACSD-49960
      - ACSD-49970-V2
      - ACSD-50116
      - ACSD-50260-V2
      - ACSD-50336
      - ACSD-50367
      - ACSD-50527
      - ACSD-50794
      - ACSD-50814
      - ACSD-50817
      - ACSD-50858
      - ACSD-51114
      - ACSD-51230
      - ACSD-51238
      - ACSD-51294
      - ACSD-51305
      - ACSD-51379
      - ACSD-51528
      - B2B-2598
      - MDVA-12304
      - MDVA-15546
      - MDVA-19640
      - MDVA-30106
      - MDVA-51204
  deploy:
    SEARCH_CONFIGURATION:
      engine: opensearch
      opensearch_server_hostname: opensearch.internal
      opensearch_server_port: '9200'
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
    CONSUMERS_WAIT_FOR_MAX_MESSAGES: false
    DATABASE_CONFIGURATION:
      connection:
        default:
          username: user
          host: database.internal
          dbname: main
          password: ''
        indexer:
          username: user
          host: database.internal
          dbname: main
          password: ''
