stage:
  global:
    # MIN_LOGGING_LEVEL: debug
    MIN_LOGGING_LEVEL: info
  deploy:
    SEARCH_CONFIGURATION:
      engine: elasticsearch6
      elasticsearch6_server_hostname: elasticsearch.internal
      elasticsearch6_server_port: '9200'
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
    CONSUMERS_WAIT_FOR_MAX_MESSAGES: false
    DATABASE_CONFIGURATION:
      connection:
        default:
          username: user
          host: database.internal
          dbname: main
          password:
