stage:
  deploy:
    SEARCH_CONFIGURATION:
      engine: elasticsearch6
      elasticsearch6_server_hostname: elasticsearch.internal
      elasticsearch6_server_port: '9200'
    CRON_CONSUMERS_RUNNER:
      cron_run: true
      max_messages: 1000
