name: deploy

on:
  push:
    branches:
      - testing-deploy
    tags:
      - "*release*-pmet-2.*-ref-*"
      - "*release*-pmet-2.*-demo-*"
      - "*release*-pmet-2.*-b2b-*

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
  TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
  MAGENTO_CLOUD_CLI_TOKEN: ${{ secrets.MAGENTO_CLOUD_CLI_TOKEN }}

jobs:

  dockerize-then-run-magento-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PMET-public/magento-cloud-manager
          submodules: true
          path: magento-cloud-manager
          ref: master
      - name: install magento-cloud cli
        run: |
          tag_to_deploy="$(echo "$GITHUB_REF" | perl -pe 's/.*(pmet.*-(ref|demo|b2b)-.*)/$1/')"
          flavor_of_tag="$(echo "$GITHUB_REF" | perl -pe 's/.*pmet.*-(ref|demo|b2b)-.*/$1/')"
          curl -sS https://accounts.magento.cloud/cli/installer | php
          projects_to_deploy=($(
            ~/.magento-cloud/bin/magento-cloud projects --format csv 2> /dev/null | perl -ne "/^(\w+),($flavor_of_tag\-[^ ]+)/ and print '\$1 '"
          ))

          echo "tag_to_deploy=$tag_to_deploy" >> tmp.txt
          echo "flavor_of_tag=$flavor_of_tag" >> tmp.txt
          echo "projects_to_deploy=${projects_to_deploy[@]}" >> tmp.txt

          [[ "$tag_to_deploy" && "$flavor_of_tag" && "${projects_to_deploy[@]}" ]] || exit 1
          curl --fail -O "https://github.com/PMET-public/magento-cloud/releases/download/$tag_to_deploy/release.tar" && {
            exit 1
            ./magento-cloud-manager/cli/bin/mcm env:deploy release.tar "${projects_to_deploy[@]}"
          }
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master
