name: run tests & relase

on:
  push:

env:
  # set a default terminal for various cmds that expect it
  TERM: xterm
  COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
  SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW: ${{ secrets.SLACK_WEBHOOK_URL_FOR_TMATE_FROM_GITHUB_WORKFLOW }}
  TMATE_AUTHORIZED_KEYS_URL: ${{ secrets.TMATE_AUTHORIZED_KEYS_URL }}
  MDM_REPO_DIR: ${{ github.workspace}}/mdm

jobs:

  dockerize-then-run-magento-app:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: PMET-public/mdm
          submodules: true
          path: mdm
          # tag: '1.0.0'
          ref: develop
      - name: bats tests
        run: |
          cd mdm
          exit 1
          ./tests/libs/bats/bin/bats -T ./tests/3-dockerize-then-run-magento-app/**/*.bats
          cd ..
      - name: get updated, generated config.php
        if: ${{ success() }}
        run: |
          app_dir="$(find "$HOME/Downloads" -maxdepth 1 -type d -name "*.app" || :)"
          "$app_dir/Contents/Resources/script" start_shell_in_app 'cat app/etc/config.php' > app/etc/config.php
          git archive --format=tar HEAD > release.tar
          tar -rf release.tar app/etc/config.php
      # be sure to create release.tar in default path
      - run: |
          echo ::set-env name=RELEASE_TAG::"${GITHUB_REF#refs/heads/}-$(git rev-parse --short HEAD)"
      - uses: PMET-public/github-release@master
        with:
          tag: ${{ env.RELEASE_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          files: release.tar
          draft: false
          gzip: false
          prerelease: false
      - name: keep alive to debug
        if: ${{ failure() }}
        uses: PMET-public/action-tmate@master
